/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package demographics;

import java.awt.Color;
import java.awt.Graphics;

/**
 *
 * @author pcy113
 */
public class DrawPanel extends javax.swing.JPanel {

	/**
	 * Creates new form DrawPanel
	 */
	public DrawPanel() {
		initComponents();
	}

	private int rows = 8, cols = 8;

	@Override
	public void paint(Graphics g) {
		g.setColor(Color.WHITE);
		g.fillRect(0, 0, super.getWidth(), super.getHeight());

		final int boardSide = Math.min(getWidth(), getHeight());

		g.translate((getWidth() - boardSide) / 2, (getHeight() - boardSide) / 2);
		
		g.setColor(Color.GRAY);
		for (int row = 0; row < rows; row++) {
			for (int col = 0; col < cols; col++) {
				double colWidth = (double) boardSide / cols;
				double rowHeight = (double) boardSide / rows;
				int x = (int) (col * colWidth);
				int y = (int) (row * rowHeight);

				if ((row + col) % 2 == 0) {
					g.fillRect(x, y, (int) colWidth, (int) rowHeight);
				}
			}
		}

		g.setColor(Color.BLACK);
		for (int x = 0; x <= cols; x++) {
			g.drawLine((int) (x * ((double) boardSide / cols)), 0, (int) (x * ((double) boardSide / cols)), boardSide);
		}
		for (int y = 0; y <= rows; y++) {
			g.drawLine(0, (int) (y * ((double) boardSide / rows)), boardSide, (int) (y * ((double) boardSide / rows)));
		}

		g.drawRect(1, 1, boardSide - 1, boardSide - 1);

		g.dispose();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

	public void setRows(int rows) {
		this.rows = rows <= 0 ? 1 : rows;
	}

	public void setCols(int cols) {
		this.cols = cols <= 0 ? 1 : cols;
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
