import java.awt.event.ActionEvent;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.nio.file.StandardOpenOption;

import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

public class MainFrame extends javax.swing.JFrame {
	private CryptoBox cryptoBox = new CryptoBox();

	/**
	 * Creates new form MainFrame
	 */
	public MainFrame() {
		initComponents();
		setTitle("CryptoBox");
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		clearTextField = new javax.swing.JTextField();
		encryptButton = new javax.swing.JButton();
		decryptButton = new javax.swing.JButton();
		cipherTextField = new javax.swing.JTextField();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		loadButton = new javax.swing.JButton();
		loadButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				loadButtonActionPerformed(evt);
			}
		});
		saveButton = new javax.swing.JButton();
		saveButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				saveButtonActionPerformed(evt);
			}
		});

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		clearTextField.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N

		encryptButton.setText("Encrypt");
		encryptButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				encryptButtonActionPerformed(evt);
			}
		});

		decryptButton.setText("Decrypt");
		decryptButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				decryptButtonActionPerformed(evt);
			}
		});

		cipherTextField.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N

		jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
		jLabel1.setText("Clear text:");

		jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
		jLabel2.setText("Encrypted message:");

		loadButton.setText("load");

		saveButton.setText("save");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup().addGap(19, 19, 19).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
						.addComponent(cipherTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 587, Short.MAX_VALUE).addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING).addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup().addComponent(encryptButton)
								.addGap(18, 18, 18).addComponent(decryptButton).addGap(18, 18, 18).addComponent(loadButton).addGap(18, 18, 18).addComponent(saveButton))
						.addComponent(clearTextField))
				.addContainerGap(18, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addGap(17, 17, 17).addComponent(jLabel1).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addComponent(clearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE).addGap(18, 18, 18)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(encryptButton).addComponent(decryptButton).addComponent(loadButton)
								.addComponent(saveButton))
						.addGap(23, 23, 23).addComponent(jLabel2).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(cipherTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE).addContainerGap(17, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	protected void loadButtonActionPerformed(ActionEvent evt) {
		JFileChooser fileChooser = new JFileChooser();
		File userDir = new File(System.getProperty("user.dir"));
		fileChooser.setCurrentDirectory(userDir);
		fileChooser.setFileFilter(new FileNameExtensionFilter("Johnny crying Files", "cry"));
		fileChooser.setDialogTitle("Load file...");
		int returnVal = fileChooser.showOpenDialog(this);

		if (returnVal == JFileChooser.APPROVE_OPTION) {
			String filename = fileChooser.getSelectedFile().getAbsolutePath();
			try {
				final String content = Files.readString(Paths.get(filename));
				clearTextField.setText(cryptoBox.decodeMessage(content));
				cipherTextField.setText(content);
			} catch (IOException e) {
				e.printStackTrace();
			}
		}
	}

	protected void saveButtonActionPerformed(ActionEvent evt) {
		JFileChooser fileChooser = new JFileChooser();
		File userDir = new File(System.getProperty("user.dir"));
		fileChooser.setCurrentDirectory(userDir);
		fileChooser.setFileFilter(new FileNameExtensionFilter("Johnny crying Files", "cry"));
		fileChooser.setDialogTitle("Save file...");
		int returnVal = fileChooser.showSaveDialog(this);

		if (returnVal == JFileChooser.APPROVE_OPTION) {
			String filename = fileChooser.getSelectedFile().getAbsolutePath();
			try {
				final String content = cryptoBox.encodeMessage(clearTextField.getText());
				cipherTextField.setText(content);
				Files.writeString(Paths.get(filename), content, StandardOpenOption.CREATE);
			} catch (IOException e) {
				e.printStackTrace();
			}
		}
	}

	private void encryptButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_encryptButtonActionPerformed
		String clearText = clearTextField.getText();
		String cipherText = cryptoBox.encodeMessage(clearText);
		cipherTextField.setText(cipherText);
	}// GEN-LAST:event_encryptButtonActionPerformed

	private void decryptButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_decryptButtonActionPerformed
		String cypher = cipherTextField.getText();
		String clearText = cryptoBox.decodeMessage(cypher);
		clearTextField.setText(clearText);
	}// GEN-LAST:event_decryptButtonActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new MainFrame().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JTextField cipherTextField;
	private javax.swing.JTextField clearTextField;
	private javax.swing.JButton decryptButton;
	private javax.swing.JButton encryptButton;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JButton loadButton;
	private javax.swing.JButton saveButton;
	// End of variables declaration//GEN-END:variables
}
