/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package demographics;

import java.awt.Color;
import java.awt.Graphics;

/**
 *
 * @author pcy113
 */
public class DrawPanel extends javax.swing.JPanel {

	/**
	 * Creates new form DrawPanel
	 */
	public DrawPanel() {
		initComponents();
	}

	@Override
	public void paint(Graphics g) {
		g.setColor(Color.YELLOW);
		g.fillRect(0, 0, getWidth(), getHeight());

		g.setColor(Color.CYAN);
		g.fillOval(0, 0, getWidth() / 2, getHeight() / 2);
		g.fillOval(getWidth() / 2, 0, getWidth() / 2, getHeight() / 2);
		g.fillOval(0, getHeight() / 2, getWidth() / 2, getHeight() / 2);
		g.fillOval(getWidth() / 2, getHeight() / 2, getWidth() / 2, getHeight() / 2);

		g.setColor(Color.RED);
		g.drawLine(0, 0, getWidth(), getHeight());
		g.drawLine(0, getHeight(), getWidth(), 0);
		g.drawRect(getWidth() / 4, getHeight() / 4, getWidth() / 2, getHeight() / 2);

		g.setColor(Color.BLACK);
		g.drawString(((MainFrame) getParent().getParent().getParent().getParent()).getjTextField1().getText(), getWidth()/2, getHeight()/2);
		
		g.dispose();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
